### ISSUE TITLE
The createXcrunch result is inconsistent with the CreateX contract calculation

### ISSUE THREAD

**Issue by kiyomiya-eth** [HrikB/createXcrunch#8]
Hello HrikB,
I try to mine salt using the following instructions:

`./target/release/createxcrunch create2 --leading 4 --code-hash 0x88c6c46ebf353a52bdbab708c23d0c81daa8134a0063a0efa4508f2d01ba1eab --caller 0x0210207386647c2E0d7CEEc33D28611c3971352E`

`./target/release/createxcrunch create3 --leading 4 --caller 0x0210207386647c2E0d7CEEc33D28611c3971352E`

But their results are inconsistent with those calculated through [CreateX contract](https://etherscan.io/address/0xba5ed099633d3b313e4d5f7bdc1305d3c28ba5ed), I also tried create2crunch posted by 0age and its results are correct, how should I solve this problem?

I use Google Translate, so I apologize for any incomprehensible reading.
![E41AE40CB6022C49631FDD8DD4EADFCC](https://github.com/HrikB/createXcrunch/assets/138036542/7d8294d0-a104-4861-80ad-64d03bc93b58)
![361CE347D5E363155BA75BE97A19FB1C](https://github.com/HrikB/createXcrunch/assets/138036542/dca67171-f6b0-4944-97c5-d095b707c27b)
![E6F1E80D5147B3C96B62DB8372957800](https://github.com/HrikB/createXcrunch/assets/138036542/0aa984a9-b27e-4583-8d44-c5622e7cbb42)
![79959F5E2442514A4AEAF344FDC97212](https://github.com/HrikB/createXcrunch/assets/138036542/0839fed3-52bc-48d8-ba8f-5cac3ac381cc)

**Comment by kiyomiya-eth** [comment]
In addition, I noticed that if I do not specify --caller, a salt like 0x5e7aeff95b283102b73a9a00000000000000000000000000000000000000000 will be generated as shown below. Is this incorrectly specifying only 0x5e7aeff95b283102b73a9a000000000000000000 can deploy the contract?

**Comment by HrikB** [comment]
Regarding your first question, when testing on etherscan, I'm not sure what it populates as the `msg.sender`. That is relevant because for CreateX, if the first 20 bytes of the salt match `msg.sender`, you will get a different output than if they don't. I personally prefer to use tenderly. I've [simulated](https://dashboard.tenderly.co/ion-protocol/money-market-v1/simulator/0109d554-eaf1-4d62-9cf2-8592c3f3091d) one of your salts for deployment and the output looks fine to me.

![image](https://github.com/HrikB/createXcrunch/assets/23041116/93d6b76d-0b2e-4893-b1a0-b026fb9639da)
![image](https://github.com/HrikB/createXcrunch/assets/23041116/8c0926f6-9bea-4adc-acbb-16087edf5e0d)

For your second question, using `0x5e7aeff95b283102b73a9a00000000000000000000000000000000000000000` does not mean only `0x5e7aeff95b283102b73a9a000000000000000000` can deploy the contract. Any user can deploy with any salt on CreateX. However, resulting address will be different if first 20 bytes and `msg.sender` are the same. So if `0x5e7aeff95b283102b73a9a000000000000000000` was deploying using that salt, the output would be different than if some other address deployed using the same salt.

**Comment by kiyomiya-eth** [comment]
Thank you very much for your answer,

I learned that etherscan seems to set msg.sender to zero address if the wallet is not connected, which affects the salt returned by function _guard(bytes32 salt) in CreateX.

I'm using tenderly [simulated ](https://www.tdly.co/shared/simulation/1c0d0ad3-9e3a-4fc5-a003-380c0f148004)with CreateX function deployCreate2(bytes32,bytes), whose deployment address is consistent with what createXcrunch found.

![1](https://github.com/HrikB/createXcrunch/assets/138036542/32627f72-cc9b-4e9a-8b4e-e0cde9ba0558)

But when I [simulated ](https://www.tdly.co/shared/simulation/aa801ca7-ec46-4f80-bc1e-8e08405d8bfc)call CreateX function computeCreate2Address(bytes32, bytes32), the result is different from createXcrunch.

![2](https://github.com/HrikB/createXcrunch/assets/138036542/e244f24d-bb76-4fb3-aef8-b766146ecbf9)

I noticed that CreateX used function _guard(bytes32 salt) to make changes to the salt I entered.

![3](https://github.com/HrikB/createXcrunch/assets/138036542/06644e4d-d535-4ad5-958d-62996ffdcce4)

I calculate and use the changed salt to [simulated ](https://www.tdly.co/shared/simulation/ecd41719-99dc-4877-9898-98e19d3dbd46)call function computeCreate2Address(bytes32,bytes32).

![4](https://github.com/HrikB/createXcrunch/assets/138036542/bc854842-0b5a-41c1-b072-ecffe8c359b9)

![5](https://github.com/HrikB/createXcrunch/assets/138036542/dddb962d-5b72-4cbd-b470-9701d479d944)

I successfully got the same value as function deployCreate2(bytes32, bytes) and createXcrunch through function computeCreate2Address(bytes32,bytes32).

Thanks again for your answer! this is very useful for deploying my contract.
